### ISSUE TITLE
Denying a Team Request doesn't work

### ISSUE THREAD

**Issue by KyleKaniecki** [KyleKaniecki/Skirmish-Issues#27]
**Bug Subsystem**: Teams

**Expected Behavior:** 
As a user, when I deny a team request, I expect the request to be deleted.

**Actual Behavior:** 
When I deny a team request, it removes it from my notifications until I click on the notifications button again.

**Reproduction Steps**: 

1. Receive a team request
2. Click deny
3. Click the notifications button again
4. The team request is still there

**Screenshots:** 
N/A

**Additional Information:** 
N/A

**Comment by SkirmishPro** [comment]
Accepting a team request doesn't work either. Not sure if you would like it reported as a separate issue.
