### ISSUE TITLE
Editing teams with a list of captains removes and re-invites current members

### ISSUE THREAD

**Issue by Lotus-Flower** [KyleKaniecki/Skirmish-Issues#28]
**Bug Subsystem**: 
Teams

**Expected Behavior:** 
When a PATCH request is sent to /teams/{teamid}/ with a JSON containing a modified list of captains, the captains list for the team should be changed accordingly.

**Actual Behavior:** 
When a PATCH request is sent to /teams/{teamid}/ with a JSON containing a modified list of captains, the existing members of the team are removed and re-invited, regardless of whether they were included/not included in the captains list. The captains list changes accordingly, but with this side effect.

**Reproduction Steps**: 

1. Create JSON for a team which modifies the captains list
2. Send JSON in a patch request to /teams/{teamid}/
3. Send a GET request to the same endpoint to check if members have been affected

**Screenshots:** 

**Additional Information:**

**Comment by KyleKaniecki** [comment]
@Lotus-Flower Can you please add in the json blob that you are sending up to the endpoint? That would really help me debug this.

Also, please add labels to the issue next time. I filter by the **bug** label 99% of the time, so I lost this for a while.

**Comment by Lotus-Flower** [comment]
![image](https://user-images.githubusercontent.com/9878534/42379528-e4959b68-80f8-11e8-9237-a7500429b0bf.png)

This is the blob sent up. When sent, this one correctly edits the list of captains, but removes all members and makes them pending members. This same behavior also happens with a blob containing just the captains field if that is helpful.
