### ISSUE TITLE
Skirm disappears after reporting conflicting results

### ISSUE THREAD

**Issue by SkirmishPro** [KyleKaniecki/Skirmish-Issues#30]
**Bug Subsystem**: 
Skirm

**Expected Behavior:** 
After two users report conflicting results in a 1v1 skirm, the skirm should remain under "Your Skirms" until the conflict is resolved.

**Actual Behavior:** 
After the conflict is reported, both users lose the visibility to the skirm. I can see it as an admin, and I can even resolve the conflict.

**Reproduction Steps**: 
1. Created a 1v1 skirm as ABain
2. I joined test4
3. I reported conflicting results
4. The listing disappeared but I could see it in the admin view and I can resolve the conflict

**Screenshots:** 
Video recording [here](https://drive.google.com/drive/u/1/folders/11oX8hFapw--fGHTLPPOFf3CymK9GYrRl?ogsrc=32).

**Additional Information:** 
I only tested this under 1v1 skirms, not teams.

**Comment by KyleKaniecki** [comment]
Confirmed, and I know why this is happening. Will fix ASAP, and moving to next release board.
