### ISSUE TITLE
Removing Pledge Access if Verification is Revoked

### ISSUE THREAD

**Issue by SkirmishPro** [KyleKaniecki/Skirmish-Issues#33]
**Bug Subsystem**: 
Skirm

**Expected Behavior:** 
If an admin revokes verification approval, the user should no longer be allowed to make a pledge.

**Actual Behavior:** 
After changing test1's status from Approved to Denied, the user still has visibility and access to pledging money on a skirm.

**Reproduction Steps**: 
1. I set test1 as approved. They gained access to pledges
2. I changed the status to anything other than Approved but they still have access.

**Screenshots:** 
N/A

**Additional Information:** 
N/A

**Comment by KyleKaniecki** [comment]
Please reference my comment on #36  for the reasoning why this happens. Closing as won't do.
