### ISSUE TITLE
Team Skirms Payment Not Processing

### ISSUE THREAD

**Issue by SkirmishPro** [KyleKaniecki/Skirmish-Issues#34]
**Bug Subsystem**: 
Skirms

**Expected Behavior:** 
When creating a Team Skirm, my payment should be processed and the page should redirect me to my new skirm.

**Actual Behavior:** 
I click "Create" and nothing happens. The paypal window briefly appears but nothing else happens.

**Reproduction Steps**: 
1. I created a team for test1 and test2
2. As test1 (the captain and only verified team member) I filled out the form to create a 2v2 skirm with a $5 pledge.
3. I click create and nothing happens (the skirm is created, is visible on the listings page, and it appears in the database but the payment does not).

**Screenshots:** 
Screen recording [here.](https://drive.google.com/drive/u/1/folders/11oX8hFapw--fGHTLPPOFf3CymK9GYrRl?ogsrc=32)

**Additional Information:** 
N/A

**Comment by KyleKaniecki** [comment]
Double checked this, and it is a valid bug. Working on fixing it now.

**Comment by KyleKaniecki** [comment]
There was actually two things that was going on here, and I believe I have fixed both of them. Pushing into testing column and deploying to staging for testing.
