### ISSUE TITLE
Entering a Tournament as Unverified and Restricted

### ISSUE THREAD

**Issue by SkirmishPro** [KyleKaniecki/Skirmish-Issues#36]
**Bug Subsystem**: 
Tournaments

**Expected Behavior:** 
If I'm unverified and live in a restricted state I should not be able to enter a paid tournament.

**Actual Behavior:** 
I'm able to enter a paid tournament as an unverified and restricted user.

**Reproduction Steps**: 
1. I created a 1v1 tournament with a $5 entry fee
2. I joined test1 (verified and unrestricted)
3. I joined test3 (verified but restricted - the payment was created and processed)
4. I joined test4 (unverified and restricted - the payment was created and processed)

**Screenshots:** 
N/A

**Additional Information:** 
N/A

**Comment by KyleKaniecki** [comment]
Based on the backend, it looks like this is actually **working as expected.**

The player signed into PayPal, accepted and signed the affidavit, and we accepted their proof on the dashboard. However, the status was put as **denied.** So the api got confused, and things were switched around.

I will change this so I take into account the full picture.
