### ISSUE TITLE
Player should only be able to be registered on one team per tournament

### ISSUE THREAD

**Issue by Lotus-Flower** [KyleKaniecki/Skirmish-Issues#41]
**Bug Subsystem**: 
Tournaments

**Expected Behavior:** 
When a player attempts to register a team for a tournament, the server should check if the player is already part of a registered team for that tournament.

**Actual Behavior:** 
Players are able to register on multiple teams in a tournament, which increases their chances to win

**Reproduction Steps**: 

1. Choose a tournament of type "teams"
2. Hit the registration endpoint as a player with an eligible team
3. Hit the registration endpoint as the same player with a second eligible team 

**Screenshots:** 
(Screenshots of the browser if value is added)

**Additional Information:** 
Anything that may be of value, such as User status, Subsystem Status (Tournament was past registration deadline, before start date, Skirm was not accepted), etc

**Comment by mgiasi** [comment]
ran into this bug though the UI. We need to ensure that when someone tries to register a team we check if any of the players on that team are already registered.
