### ISSUE TITLE
Tournament Final Match Details

### ISSUE THREAD

**Issue by SkirmishPro** [KyleKaniecki/Skirmish-Issues#49]
**Bug Subsystem**:  Tournaments

**Expected Behavior:** The "zoom-in" detail modal should display the correct teams that played in the match, their scores, trueskill, and IDs.

**Actual Behavior:** Per the screenshot, the details of the Final match (all other match details are correct) shows test1 vs test1. The final match was actually test vs test3.

**Reproduction Steps**: 
1. Create a 1v1 or team, *single elimination* tournament tournament
2. Register people into the tournament and check them all in
3. Start the tournament and report all matches until the last one
4. Once the last game happens, notice that the players are **correct** for the last game.
5. Report scores for both players, and notice how the second player get replaced by whoever won.

**Screenshots:** 
![screen shot 2018-10-17 at 1 43 09 pm](https://user-images.githubusercontent.com/28234097/47105826-0252ea00-d213-11e8-8950-1dfce6d0cc28.png)

**Additional Information:** 
This happened on a 1v1, single elimination tournament. The game was correct before I reported scores, and then changed to the error state after I reported. The game was **not** a conflict or no show report, just two game reports submitted by both players.

**Comment by KyleKaniecki** [comment]
Hmmm... interesting. This appears to happen on the backend and not on the frontend. I will look into this once I get home tonight and see if I can fix the algorithm before launch.

**Comment by KyleKaniecki** [comment]
The solution has been found and the bug has been squashed. 🐛
