### ISSUE TITLE
Can't Create a 1v1 Skirm

### ISSUE THREAD

**Issue by SkirmishPro** [KyleKaniecki/Skirmish-Issues#50]
**Bug Subsystem**:  Skirm

**Expected Behavior:** After filling out the skirm creation form, the skirm should be created.

**Actual Behavior:** After filling out the 1v1 skirm creation form, nothing happens. I click the "Create Skirm" button, nothing happens and I receive the below error (screenshot).

**Reproduction Steps**: 
1. Log in as test4/ABain
2. Click "Create" skirm and fill out the form. 1v1, no pledge, start date and time for the soonest possible. Tried with CSGO and Halo.
3. Click "Create Skirm" button and nothing happens. Receive the below error in the console.

**Screenshots:** 
![screen shot 2018-10-17 at 9 10 41 pm](https://user-images.githubusercontent.com/28234097/47125437-875cf400-d251-11e8-90aa-2ab955d7994f.png)

**Additional Information:** 
Tried creating a skirm as ABain and test4. Both 1v1 and for CSGO/Halo. I also did a hard reload but that doesn't seem to be the issue here.

**Comment by KyleKaniecki** [comment]
This issue looks like it was caused by validation I added to one vs one skirms to ensure the host can not also be the guest. I have since moved this around a little bit and it looks like the validation is still working, along with creation!
