### ISSUE TITLE
No Show Advancing Wrong Player

### ISSUE THREAD

**Issue by SkirmishPro** [KyleKaniecki/Skirmish-Issues#52]
**Bug Subsystem**: Tournament (1v1 - Double Elimination)

**Expected Behavior:** When a user reports a No Show and the admin accepts the request, the reporting player should advance.

**Actual Behavior:** When I reported a No Show as test2 for test13 (test13 being the team that did not show up), after accepting the report test13 was the team that advanced.

**Reproduction Steps**: 
1. Created a 1v1 double elimination tournament as ABain. No entry fee, Halo/Xbox, sponsored
2. In the first round, I reported a No Show as test2 against test13
3. I accepted the report as ABain but the test13 advanced. Test2 should have advanced

**Screenshots:** 
![screen shot 2018-10-17 at 10 07 14 pm](https://user-images.githubusercontent.com/28234097/47126965-086bb980-d259-11e8-90da-811fb1ec7a04.png)

**Additional Information:** 
One important note, I did try this 3 times in the first round of this tournament. The first time the error occurred (test10vtest15), the second time the report worked perfectly (test6vtest11), and the third time which is this report for test2vtest13 in which the error happened again. Not sure what's making the difference here. No errors showing up in the console.

**Comment by KyleKaniecki** [comment]
Found it, squashed it 🐛
