### ISSUE TITLE
Teams: Adding a teammate error

### ISSUE THREAD

**Issue by SkirmishPro** [KyleKaniecki/Skirmish-Issues#53]
**Bug Subsystem**: Teams

**Expected Behavior:** When creating or editing a team, adding a teammate should send an invite to the other player(s).

**Actual Behavior:** When creating or editing a team, adding a teammate generates the below error. The team is created or updated, the page just sits there.

**Reproduction Steps**: 
1. Create a team as test3 (or editing one of the existing test3 teams)
2. added test4 in the Team Members field and click Submit
3. Nothing happens and the below error is generated

**Screenshots:** 
![screen shot 2018-10-18 at 8 57 48 pm](https://user-images.githubusercontent.com/28234097/47192119-2a2c7580-d319-11e8-9c8c-86f91924dcd6.png)

**Additional Information:** 
The team is for Halo/Xbox, no avatar, no motto, no changes to the captain field

**Comment by KyleKaniecki** [comment]
Found and fixed. This bug was introduced due to the nature of allowing avatars now.
