### ISSUE TITLE
Show Pending Team Invites In Team Card

### ISSUE THREAD

**Issue by KyleKaniecki** [KyleKaniecki/Skirmish-Issues#68]
**Bug Subsystem**: 
Teams

**Expected Behavior:** 
As a user, I want the ability to view pending team invites without having to go to the edit team page

**Actual Behavior:** 
Currently, the only way to see pending team invites is by editing the team.

**Reproduction Steps**: 

1. Create a team
2. Invite others to the team
3. Go to the team listing page
4. Cry

**Screenshots:** 
![screen shot 2018-12-03 at 8 05 49 pm](https://user-images.githubusercontent.com/14900780/49411426-de9e2180-f736-11e8-99a0-ed33a9f95a42.png)
![screen shot 2018-12-03 at 8 05 55 pm](https://user-images.githubusercontent.com/14900780/49411428-e1007b80-f736-11e8-8a6e-200d0425291a.png)

**Additional Information:** 
N/A

**Test Plan:**
Steps to make sure that this is working
Note: Leave this blank unless you are the developer who fixed this
Note: Do not check things unless you are the assigned tester

**Comment by SkirmishPro** [comment]
Looks good. Pending invites are showing on the Teams page with the hour glass icon.
