### ISSUE TITLE
Pending team invites show as team members after multiple edits

### ISSUE THREAD

**Issue by mgiasi** [KyleKaniecki/Skirmish-Issues#70]
**Bug Subsystem**: teams

**Expected Behavior:** pending member invites only appear in the pending member section

**Actual Behavior:** after editing a team with pending invites, if you go to edit the team again you will see those same pending users as team members and pending members. 

**Reproduction Steps**: 

1. create a team
1. invite memebers, click submit
1. click edit again without refreshing the page

**Screenshots:** 
![image](https://user-images.githubusercontent.com/3782242/49552199-81ce7280-f8c0-11e8-887b-dd2dbe070358.png)

**Additional Information:** 
The users are not actually added as members on the team, this is a UI bug. 
Currently this functionality is hidden on prod, so lower priority for now.

**Test Plan:**
Steps to make sure that this is working
Note: Leave this blank unless you are the developer who fixed this
Note: Do not check things unless you are the assigned tester

**Comment by SkirmishPro** [comment]
I can't replicate this bug so it looks fixed to me.
