### ISSUE TITLE
Make Logging In Case Insensitive

### ISSUE THREAD

**Issue by KyleKaniecki** [KyleKaniecki/Skirmish-Issues#71]
**Bug Subsystem**: Accounts

**Expected Behavior:** 
As a user, I would like the ability to log in with my username without it being case sensitive

**Actual Behavior:** 
Currently, the login endpoint is case sensitive

**Reproduction Steps**: 

1. Create an account
2. Log out
3. Try to log back in, but with a different case
4. Cry

**Screenshots:** 
N/A

**Additional Information:** 
N/A

**Test Plan:**
Steps to make sure that this is working
Note: Leave this blank unless you are the developer who fixed this
Note: Do not check things unless you are the assigned tester

**Comment by SkirmishPro** [comment]
Works great!
