### ISSUE TITLE
Deleting A Pending Team Request Does Nothing

### ISSUE THREAD

**Issue by KyleKaniecki** [KyleKaniecki/Skirmish-Issues#72]
**Bug Subsystem**: Teams

**Expected Behavior:** 
As a user, I Would like to be able to cancel a pending team request and have it be deleted

**Actual Behavior:** 
Currently, I can delete it and it gets deleted on the UI, but it doesn't get deleted on the backend.

**Reproduction Steps**: 

1. Create a team
2. Invite other members to the team
3. Edit the team again
4. Delete some of the pending invites
5. Click edit again
6. invites are still there.

**Screenshots:** 
N/A

**Additional Information:** 
This is probably a problem in the serializer

**Test Plan:**
Steps to make sure that this is working
Note: Leave this blank unless you are the developer who fixed this
Note: Do not check things unless you are the assigned tester

**Comment by SkirmishPro** [comment]
This is working. I can see the invite appear and disappear (live) as I test it.
